// Public status API. Implementation is grouped by responsibility in status-*.js.
import { bind as bind0 } from './status-stat-values.js';
import { bind as bind1 } from './status-persona-state.js';
import { bind as bind2 } from './status-chat-session.js';
import { bind as bind3 } from './status-state-storage.js';
import { bind as bind4 } from './status-status-summary.js';
import { bind as bind5 } from './status-scene-prompt.js';
import { bind as bind6 } from './status-update-parser.js';
import { bind as bind7 } from './status-update-constraints.js';
import { bind as bind8 } from './status-apply-update.js';
import { bind as bind9 } from './status-cast-decisions.js';
import { bind as bind10 } from './status-scene-presence.js';
import { bind as bind11 } from './status-collection-updates.js';
import { bind as bind12 } from './status-collection-schema.js';
import { bind as bind13 } from './status-stat-schema.js';
import { bind as bind14 } from './status-system-presets.js';
import { bind as bind15 } from './status-checkpoints.js';

const deps = {};
bind0(deps);
bind1(deps);
bind2(deps);
bind3(deps);
bind4(deps);
bind5(deps);
bind6(deps);
bind7(deps);
bind8(deps);
bind9(deps);
bind10(deps);
bind11(deps);
bind12(deps);
bind13(deps);
bind14(deps);
bind15(deps);

export const mergeStatValue = deps.mergeStatValue;
export const resolveMaxValue = deps.resolveMaxValue;
export const lockedStats = deps.lockedStats;
export const sanitizeModelUpdate = deps.sanitizeModelUpdate;
export const promptCeiling = deps.promptCeiling;
export const highestCeiling = deps.highestCeiling;
export const isNumericStat = deps.isNumericStat;
export const describeNpcStatFields = deps.describeNpcStatFields;
export const meterHasCeiling = deps.meterHasCeiling;
export const drawsMeter = deps.drawsMeter;
export const clampToCeiling = deps.clampToCeiling;
export const getInitialStatValue = deps.getInitialStatValue;
export const getCurrentPersonaKey = deps.getCurrentPersonaKey;
export const getPlayerCard = deps.getPlayerCard;
export const getPlayerImageUrl = deps.getPlayerImageUrl;
export const seedPlayerFromMaster = deps.seedPlayerFromMaster;
export const activatePersona = deps.activatePersona;
export const syncPlayerToMaster = deps.syncPlayerToMaster;
export const getPersonaData = deps.getPersonaData;
export const rememberSwipeBase = deps.rememberSwipeBase;
export const restoreProfiles = deps.restoreProfiles;
export const getSwipeBase = deps.getSwipeBase;
export const swipeBaseRecord = deps.swipeBaseRecord;
export const setSwipeBaseAligner = deps.setSwipeBaseAligner;
export const getProfileBase = deps.getProfileBase;
export const initStatusLogic = deps.initStatusLogic;
export const PERSONA_KEY = deps.PERSONA_KEY;
export const hasOpenChat = deps.hasOpenChat;
export const getChatPersona = deps.getChatPersona;
export const rememberChatPersona = deps.rememberChatPersona;
export const restoreChatPersona = deps.restoreChatPersona;
export const SYSTEM_KEY = deps.SYSTEM_KEY;
export const getChatSystem = deps.getChatSystem;
export const restoreChatSystem = deps.restoreChatSystem;
export const loadStateFromMetadata = deps.loadStateFromMetadata;
export const saveStateToMetadata = deps.saveStateToMetadata;
export const getHistoryEntries = deps.getHistoryEntries;
export const undoLastChange = deps.undoLastChange;
export const restoreHistoryEntry = deps.restoreHistoryEntry;
export const formatCompactStatus = deps.formatCompactStatus;
export const getStatusInstructions = deps.getStatusInstructions;
export const getStatusExample = deps.getStatusExample;
export const applyScenePrompt = deps.applyScenePrompt;
export const buildSceneContext = deps.buildSceneContext;
export const parseMessageForUpdates = deps.parseMessageForUpdates;
export const splitStatKeyPart = deps.splitStatKeyPart;
export const allowedValues = deps.allowedValues;
export const takeRefusedValues = deps.takeRefusedValues;
export const constrainToOptions = deps.constrainToOptions;
export const capToLength = deps.capToLength;
export const constrainToDefinition = deps.constrainToDefinition;
export const findMatchingStatKey = deps.findMatchingStatKey;
export const applyUpdate = deps.applyUpdate;
export const findCardForName = deps.findCardForName;
export const resolveCanonicalName = deps.resolveCanonicalName;
export const CAST_PERSONA = deps.CAST_PERSONA;
export const CAST_EXCLUDED = deps.CAST_EXCLUDED;
export const getCastDecisions = deps.getCastDecisions;
export const setCastDecision = deps.setCastDecision;
export const resolvePersonaSpeaker = deps.resolvePersonaSpeaker;
export const mayJoinScene = deps.mayJoinScene;
export const reconcileScenePresence = deps.reconcileScenePresence;
export const registerActiveCharacter = deps.registerActiveCharacter;
export const removeActiveCharacter = deps.removeActiveCharacter;
export const addItem = deps.addItem;
export const removeItem = deps.removeItem;
export const syncOverrideToActiveState = deps.syncOverrideToActiveState;
export const updateMasterItem = deps.updateMasterItem;
export const renameMasterItem = deps.renameMasterItem;
export const deleteMasterItem = deps.deleteMasterItem;
export const renameCollectionId = deps.renameCollectionId;
export const statsInSystem = deps.statsInSystem;
export const renameStat = deps.renameStat;
export const renameCollectionField = deps.renameCollectionField;
export const getActiveSystem = deps.getActiveSystem;
export const migrateToActiveSystem = deps.migrateToActiveSystem;
export const setActiveSystem = deps.setActiveSystem;
export const createSystem = deps.createSystem;
export const saveSystemPreset = deps.saveSystemPreset;
export const applySystemPreset = deps.applySystemPreset;
export const getCheckpoints = deps.getCheckpoints;
export const saveCheckpoint = deps.saveCheckpoint;
export const restoreCheckpoint = deps.restoreCheckpoint;
export const deleteCheckpoint = deps.deleteCheckpoint;
export const applyCheckpointSchedule = deps.applyCheckpointSchedule;
export const deleteSystemPreset = deps.deleteSystemPreset;
export const importSystemPreset = deps.importSystemPreset;
